<?php

namespace App\Services;

class TemplateLibraryService
{
    /**
     * Get all library package templates.
     *
     * Each template has a 'type' field:
     *   - 'service'          → creates Service + Provider + Cookies + optional linked ScriptBlocker
     *   - 'script_blocker'   → creates ScriptBlocker, optionally links to existing Service
     *   - 'content_blocker'  → creates ContentBlocker, optionally links to existing Service
     *   - 'style_blocker'    → creates ScriptBlocker with blocker_type='style'
     */
    public static function getTemplates(): array
    {
        return array_merge(
            static::getServiceTemplates(),
            static::getScriptBlockerTemplates(),
            static::getContentBlockerTemplates(),
            static::getStyleBlockerTemplates(),
        );
    }

    public static function getServiceTemplates(): array
    {
        return [
            'google-tag-manager' => [
                'name' => 'Google Tag Manager',
                'type' => 'service',
                'integration_type' => 'browser_tag',
                'provider' => 'Google Ireland Limited',
                'provider_key' => 'google',
                'key' => 'google-tag-manager',
                'group' => 'marketing',
                'purpose' => 'Used to manage and deploy marketing tags, tracking pixels, and third-party scripts with consent-based loading.',
                'color' => 'info',
                'icon' => 'heroicon-o-tag',
                'version' => '1.2.0',
                'domains' => ['googletagmanager.com', 'tagmanager.google.com', 'www.googletagmanager.com'],
                'consent_mode_mapping' => [
                    'consent_signals' => ['ad_storage', 'analytics_storage', 'ad_user_data', 'ad_personalization'],
                    'default_state' => 'denied',
                    'advanced_mode' => true,
                ],
                'cookies' => [
                    ['name' => '_dc_gtm_.*', 'lifetime' => '1 Minute', 'purpose' => 'Used by DoubleClick (Google Tag Manager) to help identify the visitors by either age, gender or interests.'],
                    ['name' => '_gcl_au', 'lifetime' => '3 Months', 'purpose' => 'Store and track conversions'],
                    ['name' => '_gac_.*', 'lifetime' => '3 Months', 'purpose' => 'Contains campaign-related information for the user. Used to link Google Ads data.'],
                    ['name' => '_gat_.*', 'lifetime' => '1 Minute', 'purpose' => 'Used by Google Analytics to throttle request rate.'],
                    ['name' => '_gcl_aw', 'lifetime' => '3 Months', 'purpose' => 'Stores Google Ads click identifiers for conversion tracking.'],
                ],
                'payloads' => [
                    'opt_in' => <<<'HTML'
<script data-no-optimize="1" data-no-minify="1" data-cfasync="false">
(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','{{gtm_id}}');
</script>
HTML,
                    'opt_out' => '',
                    'fallback' => '',
                ],
                'script_blocker' => [
                    'handles' => ['google-tag-manager'],
                    'phrases' => ['googletagmanager.com/gtm.js'],
                ],
                'instructions' => '<p><strong>Setup:</strong> Enter your <strong>Google Tag Manager Container ID</strong> (e.g. GTM-XXXXXXX).</p>',
                'changelog' => [
                    '1.2.0' => [
                        'Added `_gcl_aw` cookie — stores Google Ads click identifiers for conversion tracking.',
                        'Improved consent-based script loading compatibility.',
                    ],
                    '1.1.0' => [
                        'Added `_gac_.*` cookie — campaign-related information for linking Google Ads data.',
                        'Added `_gat_.*` cookie — used by Google Analytics to throttle request rate.',
                        'Improved purpose description with consent-based loading details.',
                    ],
                    '1.0.0' => [
                        'Initial release with GTM container script, `_dc_gtm_.*` and `_gcl_au` cookies.',
                        'Auto-creates linked Script Blocker for googletagmanager.com.',
                    ],
                ],
            ],
            'google-analytics' => [
                'name' => 'Google Analytics 4',
                'type' => 'service',
                'integration_type' => 'browser_tag',
                'provider' => 'Google Ireland Limited',
                'provider_key' => 'google',
                'key' => 'google-analytics',
                'group' => 'marketing',
                'purpose' => 'Used to track website traffic and user behavior.',
                'color' => 'warning',
                'icon' => 'heroicon-o-chart-bar',
                'version' => '1.0.0',
                'domains' => ['google-analytics.com', 'googletagmanager.com'],
                'consent_mode_mapping' => [
                    'consent_signals' => ['analytics_storage'],
                    'default_state' => 'denied',
                    'advanced_mode' => true,
                ],
                'cookies' => [
                    ['name' => '_ga', 'lifetime' => '2 Years', 'purpose' => 'Session identification'],
                    ['name' => '_gid', 'lifetime' => '24 Hours', 'purpose' => 'Session identification'],
                    ['name' => '_gat', 'lifetime' => '1 Minute', 'purpose' => 'Throttle request rate'],
                ],
                'payloads' => [
                    'opt_in' => '<script async src="https://www.googletagmanager.com/gtag/js?id={{ga_id}}"></script><script>window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag(\'js\', new Date()); gtag(\'config\', \'{{ga_id}}\');</script>',
                ],
                'script_blocker' => [
                    'handles' => ['google-analytics'],
                    'phrases' => ['googletagmanager.com/gtag', 'google-analytics.com/analytics'],
                ],
                'instructions' => '<p><strong>Setup:</strong> Enter your <strong>Google Analytics 4 Measurement ID</strong> (e.g. G-XXXXXXX).</p>',
            ],
            'meta-pixel' => [
                'name' => 'Meta Pixel',
                'type' => 'service',
                'integration_type' => 'browser_tag',
                'provider' => 'Meta Platforms Ireland Limited',
                'provider_key' => 'meta',
                'key' => 'meta-pixel',
                'group' => 'marketing',
                'purpose' => 'Used for tracking conversions and optimizing Facebook ads.',
                'color' => 'primary',
                'icon' => 'heroicon-o-camera',
                'version' => '1.0.0',
                'domains' => ['connect.facebook.net', 'facebook.com', 'facebook.net'],
                'consent_mode_mapping' => [
                    'consent_signals' => ['ad_storage', 'ad_user_data'],
                    'default_state' => 'denied',
                ],
                'cookies' => [
                    ['name' => '_fbp', 'lifetime' => '3 Months', 'purpose' => 'Used by Facebook to deliver advertisement products.'],
                    ['name' => '_fbc', 'lifetime' => '3 Months', 'purpose' => 'Used by Facebook to deliver advertisement products.'],
                    ['name' => 'fr', 'lifetime' => '3 Months', 'purpose' => 'Provide ad delivery or retargeting'],
                ],
                'payloads' => [
                    'opt_in' => '<script>!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version=\'2.0\';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,\'script\',\'https://connect.facebook.net/en_US/fbevents.js\');fbq(\'init\',\'{{pixel_id}}\');fbq(\'track\',\'PageView\');</script>',
                    'opt_out' => '',
                    'fallback' => '',
                ],
                'script_blocker' => [
                    'handles' => ['meta-pixel', 'facebook-pixel'],
                    'phrases' => ['connect.facebook.net', 'fbevents.js'],
                ],
                'instructions' => '<p><strong>Setup:</strong> Enter your <strong>Meta (Facebook) Pixel ID</strong> (numbers only, e.g. 1234567890).</p>',
            ],
            'google-ads' => [
                'name' => 'Google Ads',
                'type' => 'service',
                'integration_type' => 'browser_tag',
                'provider' => 'Google Ireland Limited',
                'provider_key' => 'google',
                'key' => 'google-ads',
                'group' => 'marketing',
                'purpose' => 'Cookie by Google used for ad targeting and ad measurement.',
                'color' => 'danger',
                'icon' => 'heroicon-o-currency-dollar',
                'version' => '1.0.0',
                'domains' => ['googleads.g.doubleclick.net', 'googleadservices.com'],
                'consent_mode_mapping' => [
                    'consent_signals' => ['ad_storage', 'ad_user_data', 'ad_personalization'],
                    'default_state' => 'denied',
                    'advanced_mode' => true,
                ],
                'cookies' => [
                    ['name' => '_gcl_au', 'lifetime' => '3 Months', 'purpose' => 'Used by Google AdSense for experimenting with advertisement efficiency.'],
                    ['name' => '_gcl_aw', 'lifetime' => '3 Months', 'purpose' => 'Used to track conversions.'],
                ],
                'payloads' => [
                    'opt_in' => '<script async src="https://www.googletagmanager.com/gtag/js?id={{ga_id}}"></script><script>window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag(\'js\', new Date()); gtag(\'config\', \'{{ga_id}}\');</script>',
                ],
                'instructions' => '<p><strong>Setup:</strong> Enter your <strong>Google Ads Conversion ID</strong> (e.g. AW-XXXXXXX).</p>',
            ],
            'linkedin-insight' => [
                'name' => 'LinkedIn Insight Tag',
                'type' => 'service',
                'integration_type' => 'browser_tag',
                'provider' => 'LinkedIn Ireland Unlimited Company',
                'provider_key' => 'linkedin',
                'key' => 'linkedin-insight',
                'group' => 'marketing',
                'purpose' => 'LinkedIn tracking and advertising pixel.',
                'color' => 'info',
                'icon' => 'heroicon-o-users',
                'version' => '1.0.0',
                'domains' => ['snap.licdn.com', 'linkedin.com'],
                'consent_mode_mapping' => [
                    'consent_signals' => ['ad_storage', 'ad_user_data'],
                    'default_state' => 'denied',
                ],
                'cookies' => [
                    ['name' => 'bcookie', 'lifetime' => '2 Years', 'purpose' => 'Browser Identifier cookie to uniquely identify devices accessing LinkedIn.'],
                    ['name' => 'li_sugr', 'lifetime' => '3 Months', 'purpose' => 'Used to make a probabilistic match of a user\'s identity.'],
                ],
                'payloads' => [
                    'opt_in' => '<script type="text/javascript">_linkedin_partner_id = "{{pixel_id}}"; window._linkedin_data_partner_ids = window._linkedin_data_partner_ids || []; window._linkedin_data_partner_ids.push(_linkedin_partner_id);</script><script type="text/javascript">(function(l) { if (!l){window.lintrk = function(a,b){window.lintrk.q.push([a,b])}; window.lintrk.q=[]} var s = document.getElementsByTagName("script")[0]; var b = document.createElement("script"); b.type = "text/javascript";b.async = true; b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js"; s.parentNode.insertBefore(b, s);})(window.lintrk);</script>',
                ],
                'script_blocker' => [
                    'handles' => ['linkedin-insight'],
                    'phrases' => ['snap.licdn.com', 'li.lms-analytics'],
                ],
                'instructions' => '<p><strong>Setup:</strong> Enter your <strong>LinkedIn Insight Partner ID</strong>.</p>',
            ],
            'tiktok-pixel' => [
                'name' => 'TikTok Pixel',
                'type' => 'service',
                'integration_type' => 'browser_tag',
                'provider' => 'TikTok Information Technologies UK Limited',
                'provider_key' => 'tiktok',
                'key' => 'tiktok-pixel',
                'group' => 'marketing',
                'purpose' => 'TikTok tracking for conversion measurement and ad targeting.',
                'color' => 'gray',
                'icon' => 'heroicon-o-video-camera',
                'version' => '1.0.0',
                'domains' => ['analytics.tiktok.com', 'tiktok.com'],
                'consent_mode_mapping' => [
                    'consent_signals' => ['ad_storage', 'ad_user_data'],
                    'default_state' => 'denied',
                ],
                'cookies' => [
                    ['name' => '_ttp', 'lifetime' => '13 Months', 'purpose' => 'Used to measure and improve the performance of your advertising campaigns.'],
                ],
                'payloads' => [
                    'opt_in' => '<script>!function (w, d, t) { w.TiktokAnalyticsObject=t;var ttq=w[t]=w[t]||[];ttq.methods=["page","track","identify","instances","debug","on","off","once","ready","alias","group","enableCookie","disableCookie"];ttq.setAndDefer=function(t,e){t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}};for(var i=0;i<ttq.methods.length;i++)ttq.setAndDefer(ttq,ttq.methods[i]);ttq.instance=function(t){for(var e=ttq._i[t]||[],n=0;n<ttq.methods.length;n++)ttq.setAndDefer(e,ttq.methods[n]);return e};ttq.load=function(e,n){var i="https://analytics.tiktok.com/i18n/pixel/events.js";ttq._i=ttq._i||{},ttq._i[e]=[],ttq._i[e]._u=i,ttq._t=ttq._t||{},ttq._t[e]=+new Date,ttq._o=ttq._o||{},ttq._o[e]=n||{};var o=document.createElement("script");o.type="text/javascript",o.async=!0,o.src=i+"?sdkid="+e+"&lib="+t;var a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(o,a)}; ttq.load(\'{{pixel_id}}\'); ttq.page(); }(window, document, \'ttq\');</script>',
                ],
                'script_blocker' => [
                    'handles' => ['tiktok-pixel'],
                    'phrases' => ['analytics.tiktok.com'],
                ],
                'instructions' => '<p><strong>Setup:</strong> Enter your <strong>TikTok Pixel ID</strong>.</p>',
            ],
            'hotjar' => [
                'name' => 'Hotjar',
                'type' => 'service',
                'integration_type' => 'browser_tag',
                'provider' => 'Hotjar Ltd.',
                'provider_key' => 'hotjar',
                'key' => 'hotjar',
                'group' => 'marketing',
                'purpose' => 'Used for heatmaps, session recordings, and user feedback.',
                'color' => 'danger',
                'icon' => 'heroicon-o-fire',
                'version' => '1.0.0',
                'domains' => ['static.hotjar.com', 'hotjar.com'],
                'consent_mode_mapping' => [
                    'consent_signals' => ['analytics_storage'],
                    'default_state' => 'denied',
                ],
                'cookies' => [
                    ['name' => '_hjSessionUser_*', 'lifetime' => '1 Year', 'purpose' => 'Set when a user first lands on a page. Persists the Hotjar User ID.'],
                    ['name' => '_hjSession_*', 'lifetime' => '30 Minutes', 'purpose' => 'Holds current session data.'],
                    ['name' => '_hjid', 'lifetime' => '1 Year', 'purpose' => 'Set when the customer first lands on a page with the Hotjar script.'],
                ],
                'payloads' => [
                    'opt_in' => '<script>(function(h,o,t,j,a,r){h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};h._hjSettings={hjid:\'{{hotjar_id}}\',hjsv:6};a=o.getElementsByTagName(\'head\')[0];r=o.createElement(\'script\');r.async=1;r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;a.appendChild(r);})(window,document,\'https://static.hotjar.com/c/hotjar-\',\'.js?sv=\');</script>',
                ],
                'script_blocker' => [
                    'handles' => ['hotjar'],
                    'phrases' => ['static.hotjar.com', 'hotjar.com'],
                ],
                'instructions' => '<p><strong>Setup:</strong> Enter your <strong>Hotjar Site ID</strong>.</p>',
            ],
            'hubspot' => [
                'name' => 'HubSpot',
                'type' => 'service',
                'integration_type' => 'browser_tag',
                'provider' => 'HubSpot, Inc.',
                'provider_key' => 'hubspot',
                'key' => 'hubspot',
                'group' => 'marketing',
                'purpose' => 'Used for CRM, marketing automation, and analytics tracking.',
                'color' => 'orange',
                'icon' => 'heroicon-o-megaphone',
                'version' => '1.0.0',
                'domains' => ['js.hs-scripts.com', 'js.hsforms.net', 'js.hs-analytics.net'],
                'consent_mode_mapping' => [
                    'consent_signals' => ['analytics_storage', 'ad_user_data'],
                    'default_state' => 'denied',
                ],
                'cookies' => [
                    ['name' => '__hstc', 'lifetime' => '13 Months', 'purpose' => 'The main cookie for tracking visitors.'],
                    ['name' => 'hubspotutk', 'lifetime' => '13 Months', 'purpose' => 'Keeps track of a visitor\'s identity.'],
                    ['name' => '__hssc', 'lifetime' => '30 Minutes', 'purpose' => 'Keeps track of sessions.'],
                ],
                'payloads' => [
                    'opt_in' => '<script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/{{hubspot_id}}.js"></script>',
                ],
                'script_blocker' => [
                    'handles' => ['hubspot'],
                    'phrases' => ['js.hs-scripts.com', 'js.hsforms.net', 'js.hs-analytics.net'],
                ],
                'instructions' => '<p><strong>Setup:</strong> Enter your <strong>HubSpot Portal ID</strong>.</p>',
            ],
            'matomo' => [
                'name' => 'Matomo',
                'type' => 'service',
                'integration_type' => 'browser_tag',
                'provider' => 'InnoCraft Ltd.',
                'provider_key' => 'matomo',
                'key' => 'matomo',
                'group' => 'marketing',
                'purpose' => 'Privacy-focused web analytics platform.',
                'color' => 'success',
                'icon' => 'heroicon-o-chart-pie',
                'version' => '1.0.0',
                'domains' => [],
                'consent_mode_mapping' => [
                    'consent_signals' => ['analytics_storage'],
                    'default_state' => 'denied',
                ],
                'cookies' => [
                    ['name' => '_pk_id.*', 'lifetime' => '13 Months', 'purpose' => 'Used to store a few details about the user such as the unique visitor ID.'],
                    ['name' => '_pk_ses.*', 'lifetime' => '30 Minutes', 'purpose' => 'Short lived cookie used to temporarily store data for the visit.'],
                ],
                'payloads' => [
                    'opt_in' => '<script>var _paq=window._paq=window._paq||[];_paq.push(["trackPageView"]);_paq.push(["enableLinkTracking"]);(function(){var u="{{matomo_url}}";_paq.push(["setTrackerUrl",u+"matomo.php"]);_paq.push(["setSiteId","{{matomo_site_id}}"]);var d=document,g=d.createElement("script"),s=d.getElementsByTagName("script")[0];g.async=true;g.src=u+"matomo.js";s.parentNode.insertBefore(g,s);})();</script>',
                ],
                'instructions' => '<p><strong>Setup:</strong> Enter your <strong>Matomo URL</strong> and <strong>Site ID</strong>.</p>',
            ],
            'vimeo' => [
                'name' => 'Vimeo',
                'type' => 'service',
                'integration_type' => 'embed_provider',
                'provider' => 'Vimeo.com, Inc.',
                'provider_key' => 'vimeo',
                'key' => 'vimeo',
                'group' => 'external_media',
                'purpose' => 'Used to display embedded video content from Vimeo.',
                'color' => 'info',
                'icon' => 'heroicon-o-play',
                'version' => '1.0.0',
                'domains' => ['vimeo.com', 'player.vimeo.com'],
                'supports_accept_once' => true,
                'supports_accept_provider' => true,
                'cookies' => [
                    ['name' => 'vuid', 'lifetime' => '2 Years', 'purpose' => 'Stores the user\'s usage history for the Vimeo video player.'],
                ],
                'payloads' => [],
                'instructions' => '<p><strong>Note:</strong> This service unblocks Vimeo iframes on consent.</p>',
            ],
            'youtube' => [
                'name' => 'YouTube',
                'type' => 'service',
                'integration_type' => 'embed_provider',
                'provider' => 'Google Ireland Limited',
                'provider_key' => 'youtube',
                'key' => 'youtube',
                'group' => 'external_media',
                'purpose' => 'Used to display embedded video content and track viewing behavior.',
                'color' => 'danger',
                'icon' => 'heroicon-o-video-camera',
                'version' => '1.0.0',
                'domains' => ['youtube.com', 'youtu.be', 'youtube-nocookie.com', 'www.youtube.com'],
                'supports_accept_once' => true,
                'supports_accept_provider' => true,
                'cookies' => [
                    ['name' => 'VISITOR_INFO1_LIVE', 'lifetime' => '6 Months', 'purpose' => 'Estimate bandwidth'],
                    ['name' => 'YSC', 'lifetime' => 'Session', 'purpose' => 'Register unique ID for statistics'],
                ],
                'payloads' => [],
                'instructions' => '<p><strong>Note:</strong> This service unblocks YouTube iframes on consent.</p>',
            ],
            'google-maps' => [
                'name' => 'Google Maps',
                'type' => 'service',
                'integration_type' => 'embed_provider',
                'provider' => 'Google Ireland Limited',
                'provider_key' => 'google-maps',
                'key' => 'google-maps',
                'group' => 'external_media',
                'purpose' => 'Used to display interactive maps and location data.',
                'color' => 'success',
                'icon' => 'heroicon-o-map',
                'version' => '1.0.0',
                'domains' => ['maps.google.com', 'www.google.com', 'maps.googleapis.com'],
                'supports_accept_once' => true,
                'supports_accept_provider' => true,
                'cookies' => [
                    ['name' => 'NID', 'lifetime' => '6 Months', 'purpose' => 'Contains a unique ID Google uses to remember your preferences.'],
                ],
                'payloads' => [],
                'instructions' => '<p><strong>Note:</strong> This service unblocks Google Maps embeds on consent.</p>',
            ],
            'twitter' => [
                'name' => 'Twitter / X',
                'type' => 'service',
                'integration_type' => 'embed_provider',
                'provider' => 'Twitter International Unlimited Company',
                'provider_key' => 'x',
                'key' => 'twitter',
                'group' => 'external_media',
                'purpose' => 'Used to unblock Twitter tweets & timeline embeds.',
                'color' => 'gray',
                'icon' => 'heroicon-o-chat-bubble-left',
                'version' => '1.0.0',
                'domains' => ['twitter.com', 'x.com', 'platform.twitter.com', 'syndication.twitter.com'],
                'supports_accept_once' => true,
                'supports_accept_provider' => true,
                'cookies' => [
                    ['name' => 'gt', 'lifetime' => 'Session', 'purpose' => 'Guest token used to authenticate unlogged users.'],
                    ['name' => 'personalization_id', 'lifetime' => '2 Years', 'purpose' => 'Stores the user\'s personalization preferences.'],
                ],
                'payloads' => [],
                'instructions' => '<p><strong>Note:</strong> This service unblocks Twitter embeds on consent.</p>',
            ],
            'instagram' => [
                'name' => 'Instagram',
                'type' => 'service',
                'integration_type' => 'embed_provider',
                'provider' => 'Meta Platforms Ireland Ltd.',
                'provider_key' => 'instagram',
                'key' => 'instagram',
                'group' => 'external_media',
                'purpose' => 'Used to unblock Instagram post embeds.',
                'color' => 'rose',
                'icon' => 'heroicon-o-photo',
                'version' => '1.0.0',
                'domains' => ['instagram.com', 'www.instagram.com', 'instagr.am'],
                'supports_accept_once' => true,
                'supports_accept_provider' => true,
                'cookies' => [
                    ['name' => 'csrftoken', 'lifetime' => '1 Year', 'purpose' => 'Helps prevent Cross-Site Request Forgery (CSRF) attacks.'],
                ],
                'payloads' => [],
                'instructions' => '<p><strong>Note:</strong> This service unblocks Instagram embeds on consent.</p>',
            ],
            'stripe' => [
                'name' => 'Stripe Payments',
                'type' => 'service',
                'integration_type' => 'functional_widget',
                'provider' => 'Stripe, Inc.',
                'provider_key' => 'stripe',
                'key' => 'stripe',
                'group' => 'essential',
                'purpose' => 'Used to process secure payments and prevent fraud.',
                'color' => 'purple',
                'icon' => 'heroicon-o-credit-card',
                'version' => '1.0.0',
                'domains' => ['js.stripe.com', 'stripe.com', 'api.stripe.com'],
                'cookies' => [
                    ['name' => '__stripe_mid', 'lifetime' => '1 Year', 'purpose' => 'Fraud prevention'],
                    ['name' => '__stripe_sid', 'lifetime' => '30 Minutes', 'purpose' => 'Fraud prevention'],
                ],
                'payloads' => [],
                'instructions' => '<p><strong>Note:</strong> Essential service for payment processing.</p>',
            ],
            'paypal' => [
                'name' => 'PayPal',
                'type' => 'service',
                'integration_type' => 'functional_widget',
                'provider' => 'PayPal, Inc.',
                'provider_key' => 'paypal',
                'key' => 'paypal',
                'group' => 'essential',
                'purpose' => 'Used to process payments securely.',
                'color' => 'info',
                'icon' => 'heroicon-o-currency-dollar',
                'version' => '1.0.0',
                'domains' => ['paypal.com', 'paypalobjects.com'],
                'cookies' => [
                    ['name' => 'ts', 'lifetime' => 'Session', 'purpose' => 'Store session details'],
                    ['name' => 'ts_c', 'lifetime' => '3 Years', 'purpose' => 'Store security settings'],
                ],
                'payloads' => [],
                'instructions' => '<p><strong>Note:</strong> Essential service for payment processing.</p>',
            ],
            'pinterest-tag' => [
                'name' => 'Pinterest Tag',
                'type' => 'service',
                'integration_type' => 'browser_tag',
                'provider' => 'Pinterest Europe Ltd.',
                'provider_key' => 'pinterest',
                'key' => 'pinterest-tag',
                'group' => 'marketing',
                'purpose' => 'Used for Pinterest conversion tracking and audience targeting.',
                'color' => 'danger',
                'icon' => 'heroicon-o-heart',
                'version' => '1.0.0',
                'domains' => ['ct.pinterest.com', 's.pinimg.com', 'pinterest.com'],
                'consent_mode_mapping' => [
                    'consent_signals' => ['ad_storage', 'ad_user_data'],
                    'default_state' => 'denied',
                ],
                'cookies' => [
                    ['name' => '_pinterest_sess', 'lifetime' => '1 Year', 'purpose' => 'Login session identification.'],
                    ['name' => '_pin_unauth', 'lifetime' => '1 Year', 'purpose' => 'Tracking unauthenticated users.'],
                ],
                'payloads' => [
                    'opt_in' => '<script>!function(e){if(!window.pintrk){window.pintrk=function(){window.pintrk.queue.push(Array.prototype.slice.call(arguments))};var n=window.pintrk;n.queue=[],n.version="3.0";var t=document.createElement("script");t.async=!0,t.src=e;var r=document.getElementsByTagName("script")[0];r.parentNode.insertBefore(t,r)}}("https://s.pinimg.com/ct/core.js");pintrk("load","{{pinterest_id}}");pintrk("page");</script>',
                ],
                'script_blocker' => [
                    'handles' => ['pinterest-tag'],
                    'phrases' => ['s.pinimg.com/ct/core.js', 'ct.pinterest.com'],
                ],
                'instructions' => '<p><strong>Setup:</strong> Enter your <strong>Pinterest Tag ID</strong>.</p>',
            ],
            'clarity' => [
                'name' => 'Microsoft Clarity',
                'type' => 'service',
                'integration_type' => 'browser_tag',
                'provider' => 'Microsoft Corporation',
                'provider_key' => 'microsoft',
                'key' => 'clarity',
                'group' => 'marketing',
                'purpose' => 'Used for heatmaps, session recordings, and behavioral analytics.',
                'color' => 'cyan',
                'icon' => 'heroicon-o-eye',
                'version' => '1.0.0',
                'domains' => ['clarity.ms', 'www.clarity.ms'],
                'consent_mode_mapping' => [
                    'consent_signals' => ['analytics_storage'],
                    'default_state' => 'denied',
                ],
                'cookies' => [
                    ['name' => '_clck', 'lifetime' => '1 Year', 'purpose' => 'Persists the Clarity User ID and preferences.'],
                    ['name' => '_clsk', 'lifetime' => '1 Day', 'purpose' => 'Connects multiple page views by a user into a single Clarity session.'],
                ],
                'payloads' => [
                    'opt_in' => '<script type="text/javascript">(function(c,l,a,r,i,t,y){c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);})(window,document,"clarity","script","{{clarity_id}}");</script>',
                ],
                'script_blocker' => [
                    'handles' => ['clarity'],
                    'phrases' => ['clarity.ms/tag'],
                ],
                'instructions' => '<p><strong>Setup:</strong> Enter your <strong>Microsoft Clarity Project ID</strong>.</p>',
            ],

            // ── Analytics & CDP Services ──────────────────────────────────

            'segment' => [
                'name' => 'Segment',
                'type' => 'service',
                'integration_type' => 'browser_tag',
                'provider' => 'Twilio Inc.',
                'provider_key' => 'segment',
                'key' => 'segment',
                'group' => 'statistics',
                'purpose' => 'Customer Data Platform that routes analytics events to downstream tools.',
                'color' => 'emerald',
                'icon' => 'heroicon-o-arrows-right-left',
                'version' => '1.0.0',
                'domains' => ['cdn.segment.com', 'api.segment.io'],
                'consent_mode_mapping' => [
                    'consent_signals' => ['analytics_storage'],
                    'default_state' => 'denied',
                ],
                'cookies' => [
                    ['name' => 'ajs_anonymous_id', 'lifetime' => '1 Year', 'purpose' => 'Segment anonymous visitor identifier.'],
                    ['name' => 'ajs_user_id', 'lifetime' => '1 Year', 'purpose' => 'Segment identified user identifier.'],
                ],
                'payloads' => [
                    'opt_in' => '<script>!function(){var i="analytics",analytics=window[i]=window[i]||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","screen","once","off","on","addSourceMiddleware","addIntegrationMiddleware","setAnonymousId","addDestinationMiddleware","register"];analytics.factory=function(e){return function(){if(window[i].initialized)return window[i][e].apply(window[i],arguments);var n=Array.prototype.slice.call(arguments);if(["track","screen","alias","group","page","identify"].indexOf(e)>-1){var c=document.querySelector("link[rel=canonical]");n.push({__t:"bpc",c:c&&c.getAttribute("href")||void 0,p:location.pathname,u:location.href,s:location.search,t:document.title,r:document.referrer})}n.unshift(e);analytics.push(n);return analytics}};for(var n=0;n<analytics.methods.length;n++){var key=analytics.methods[n];analytics[key]=analytics.factory(key)}analytics.load=function(key,n){var t=document.createElement("script");t.type="text/javascript";t.async=!0;t.setAttribute("data-global-segment-analytics-key",i);t.src="https://cdn.segment.com/analytics.js/v1/"+key+"/analytics.min.js";var r=document.getElementsByTagName("script")[0];r.parentNode.insertBefore(t,r);analytics._loadOptions=n};analytics._writeKey="{{segment_write_key}}";analytics.SNIPPET_VERSION="5.2.1";analytics.load("{{segment_write_key}}");analytics.page();}}();</script>',
                ],
                'script_blocker' => [
                    'handles' => ['segment'],
                    'phrases' => ['cdn.segment.com', 'api.segment.io'],
                ],
                'instructions' => '<p><strong>Setup:</strong> Enter your <strong>Segment Write Key</strong>.</p>',
            ],
            'amplitude' => [
                'name' => 'Amplitude',
                'type' => 'service',
                'integration_type' => 'browser_tag',
                'provider' => 'Amplitude, Inc.',
                'provider_key' => 'amplitude',
                'key' => 'amplitude',
                'group' => 'statistics',
                'purpose' => 'Product analytics platform for tracking user behavior and engagement.',
                'color' => 'indigo',
                'icon' => 'heroicon-o-chart-bar-square',
                'version' => '1.0.0',
                'domains' => ['cdn.amplitude.com', 'api2.amplitude.com'],
                'consent_mode_mapping' => [
                    'consent_signals' => ['analytics_storage'],
                    'default_state' => 'denied',
                ],
                'cookies' => [
                    ['name' => 'amp_*', 'lifetime' => '1 Year', 'purpose' => 'Amplitude device and session identifiers.'],
                ],
                'payloads' => [
                    'opt_in' => '<script src="https://cdn.amplitude.com/libs/analytics-browser-2.11.1-min.js.gz"></script><script>window.amplitude.init("{{amplitude_api_key}}");</script>',
                ],
                'script_blocker' => [
                    'handles' => ['amplitude'],
                    'phrases' => ['cdn.amplitude.com', 'api2.amplitude.com'],
                ],
                'instructions' => '<p><strong>Setup:</strong> Enter your <strong>Amplitude API Key</strong>.</p>',
            ],
            'mixpanel' => [
                'name' => 'Mixpanel',
                'type' => 'service',
                'integration_type' => 'browser_tag',
                'provider' => 'Mixpanel, Inc.',
                'provider_key' => 'mixpanel',
                'key' => 'mixpanel',
                'group' => 'statistics',
                'purpose' => 'Product analytics for tracking user interactions, funnels, and retention.',
                'color' => 'violet',
                'icon' => 'heroicon-o-beaker',
                'version' => '1.0.0',
                'domains' => ['cdn.mxpnl.com', 'api-js.mixpanel.com', 'mixpanel.com'],
                'consent_mode_mapping' => [
                    'consent_signals' => ['analytics_storage'],
                    'default_state' => 'denied',
                ],
                'cookies' => [
                    ['name' => 'mp_*_mixpanel', 'lifetime' => '1 Year', 'purpose' => 'Mixpanel user tracking and session data.'],
                ],
                'payloads' => [
                    'opt_in' => '<script src="https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js"></script><script>mixpanel.init("{{mixpanel_token}}",{track_pageview:"url-with-tag-params"});</script>',
                ],
                'script_blocker' => [
                    'handles' => ['mixpanel'],
                    'phrases' => ['cdn.mxpnl.com', 'api-js.mixpanel.com'],
                ],
                'instructions' => '<p><strong>Setup:</strong> Enter your <strong>Mixpanel Project Token</strong>.</p>',
            ],

            // ── Server-Side Destinations ──────────────────────────────────

            'meta-conversions-api' => [
                'name' => 'Meta Conversions API',
                'type' => 'service',
                'integration_type' => 'server_destination',
                'provider' => 'Meta Platforms Ireland Ltd.',
                'provider_key' => 'meta',
                'key' => 'meta-conversions-api',
                'group' => 'marketing',
                'purpose' => 'Server-side event forwarding to Meta for conversion tracking without browser cookies.',
                'color' => 'info',
                'icon' => 'heroicon-o-server-stack',
                'version' => '1.0.0',
                'domains' => ['graph.facebook.com'],
                'consent_mode_mapping' => [
                    'consent_signals' => ['ad_storage', 'ad_user_data'],
                    'default_state' => 'denied',
                ],
                'cookies' => [
                    ['name' => '_fbp', 'lifetime' => '3 Months', 'purpose' => 'Facebook browser pixel ID for event deduplication.'],
                    ['name' => '_fbc', 'lifetime' => '3 Months', 'purpose' => 'Facebook click ID from ad click-through.'],
                ],
                'payloads' => [
                    'opt_in' => '<script>/* Meta CAPI: Browser-side event emitter for server-side forwarding. */window.YCookiesCAPI=window.YCookiesCAPI||{queue:[]};window.YCookiesCAPI.track=function(e,d){var ev={event_name:e,event_id:"evt_"+Date.now()+"_"+Math.random().toString(36).substr(2,8),data:d||{},timestamp:Date.now()};window.YCookiesCAPI.queue.push(ev);window.dispatchEvent(new CustomEvent("ycookies:capi_event",{detail:ev}));};window.YCookiesCAPI.track("PageView");</script>',
                ],
                'instructions' => '<p><strong>Setup:</strong> This is a <strong>server-side destination</strong>. Events are emitted via <code>window.YCookiesCAPI.track()</code> and must be forwarded to Meta\'s Conversions API from your backend. Requires a Meta Pixel ID and Access Token configured server-side.</p>',
            ],
            'tiktok-events-api' => [
                'name' => 'TikTok Events API',
                'type' => 'service',
                'integration_type' => 'server_destination',
                'provider' => 'TikTok Technology Limited',
                'provider_key' => 'tiktok',
                'key' => 'tiktok-events-api',
                'group' => 'marketing',
                'purpose' => 'Server-side event forwarding to TikTok for conversion tracking and audience building.',
                'color' => 'fuchsia',
                'icon' => 'heroicon-o-server-stack',
                'version' => '1.0.0',
                'domains' => ['business-api.tiktok.com', 'analytics.tiktok.com'],
                'consent_mode_mapping' => [
                    'consent_signals' => ['ad_storage', 'ad_user_data'],
                    'default_state' => 'denied',
                ],
                'cookies' => [
                    ['name' => '_ttp', 'lifetime' => '13 Months', 'purpose' => 'TikTok Pixel cookie for event deduplication.'],
                    ['name' => 'ttclid', 'lifetime' => '3 Months', 'purpose' => 'TikTok click identifier from ad campaigns.'],
                ],
                'payloads' => [
                    'opt_in' => '<script>/* TikTok Events API: Browser-side event emitter for server-side forwarding. */window.YCookiesTTEAPI=window.YCookiesTTEAPI||{queue:[]};window.YCookiesTTEAPI.track=function(e,d){var ev={event:e,event_id:"ttevt_"+Date.now()+"_"+Math.random().toString(36).substr(2,8),properties:d||{},timestamp:Date.now()};window.YCookiesTTEAPI.queue.push(ev);window.dispatchEvent(new CustomEvent("ycookies:tteapi_event",{detail:ev}));};window.YCookiesTTEAPI.track("Pageview");</script>',
                ],
                'instructions' => '<p><strong>Setup:</strong> This is a <strong>server-side destination</strong>. Events are emitted via <code>window.YCookiesTTEAPI.track()</code> and must be forwarded to TikTok\'s Events API from your backend. Requires a TikTok Pixel ID and Access Token configured server-side.</p>',
            ],
        ];
    }

    public static function getScriptBlockerTemplates(): array
    {
        return [
            'sb-cleverreach' => [
                'name' => 'CleverReach',
                'type' => 'script_blocker',
                'provider' => 'CleverReach GmbH & Co. KG',
                'key' => 'sb-cleverreach',
                'purpose' => 'Blocks CleverReach email marketing scripts until consent is given.',
                'color' => 'orange',
                'icon' => 'heroicon-o-envelope',
                'version' => '1.0.0',
                'handles' => ['cleverreach'],
                'phrases' => ['static.cleverreach.com'],
                'linked_service_key' => null,
            ],
            'sb-convertbox' => [
                'name' => 'ConvertBox',
                'type' => 'script_blocker',
                'provider' => 'ConvertBox',
                'key' => 'sb-convertbox',
                'purpose' => 'Blocks ConvertBox popup/opt-in scripts until consent is given.',
                'color' => 'info',
                'icon' => 'heroicon-o-chat-bubble-bottom-center-text',
                'version' => '1.0.0',
                'handles' => ['convertbox'],
                'phrases' => ['app.convertbox.com'],
                'linked_service_key' => null,
            ],
            'sb-mailchimp' => [
                'name' => 'Mailchimp',
                'type' => 'script_blocker',
                'provider' => 'The Rocket Science Group LLC',
                'key' => 'sb-mailchimp',
                'purpose' => 'Blocks Mailchimp tracking and form scripts until consent is given.',
                'color' => 'warning',
                'icon' => 'heroicon-o-envelope-open',
                'version' => '1.0.0',
                'handles' => ['mailchimp', 'mc-validate'],
                'phrases' => ['chimpstatic.com', 'list-manage.com/subscribe'],
                'linked_service_key' => null,
            ],
            'sb-intercom' => [
                'name' => 'Intercom',
                'type' => 'script_blocker',
                'provider' => 'Intercom R&D Unlimited Company',
                'key' => 'sb-intercom',
                'purpose' => 'Blocks Intercom chat widget scripts until consent is given.',
                'color' => 'info',
                'icon' => 'heroicon-o-chat-bubble-left-right',
                'version' => '1.0.0',
                'handles' => ['intercom'],
                'phrases' => ['widget.intercom.io', 'intercomcdn.com'],
                'linked_service_key' => null,
            ],
            'sb-crisp' => [
                'name' => 'Crisp Chat',
                'type' => 'script_blocker',
                'provider' => 'Crisp IM SAS',
                'key' => 'sb-crisp',
                'purpose' => 'Blocks Crisp live chat scripts until consent is given.',
                'color' => 'purple',
                'icon' => 'heroicon-o-chat-bubble-oval-left-ellipsis',
                'version' => '1.0.0',
                'handles' => ['crisp'],
                'phrases' => ['client.crisp.chat'],
                'linked_service_key' => null,
            ],
            'sb-tidio' => [
                'name' => 'Tidio Chat',
                'type' => 'script_blocker',
                'provider' => 'Tidio LLC',
                'key' => 'sb-tidio',
                'purpose' => 'Blocks Tidio live chat scripts until consent is given.',
                'color' => 'sky',
                'icon' => 'heroicon-o-chat-bubble-left-ellipsis',
                'version' => '1.0.0',
                'handles' => ['tidio'],
                'phrases' => ['code.tidio.co'],
                'linked_service_key' => null,
            ],
            'sb-recaptcha' => [
                'name' => 'Google reCAPTCHA',
                'type' => 'script_blocker',
                'provider' => 'Google Ireland Limited',
                'key' => 'sb-recaptcha',
                'purpose' => 'Blocks Google reCAPTCHA scripts until consent is given.',
                'color' => 'info',
                'icon' => 'heroicon-o-shield-check',
                'version' => '1.0.0',
                'handles' => ['google-recaptcha'],
                'phrases' => ['google.com/recaptcha', 'gstatic.com/recaptcha'],
                'linked_service_key' => null,
            ],
            'sb-mouseflow' => [
                'name' => 'Mouseflow',
                'type' => 'script_blocker',
                'provider' => 'Mouseflow ApS',
                'key' => 'sb-mouseflow',
                'purpose' => 'Blocks Mouseflow session replay and heatmap scripts.',
                'color' => 'teal',
                'icon' => 'heroicon-o-cursor-arrow-ripple',
                'version' => '1.0.0',
                'handles' => ['mouseflow'],
                'phrases' => ['cdn.mouseflow.com'],
                'linked_service_key' => null,
            ],
            'sb-zendesk' => [
                'name' => 'Zendesk Chat',
                'type' => 'script_blocker',
                'provider' => 'Zendesk, Inc.',
                'key' => 'sb-zendesk',
                'purpose' => 'Blocks Zendesk customer support widget scripts.',
                'color' => 'emerald',
                'icon' => 'heroicon-o-lifebuoy',
                'version' => '1.0.0',
                'handles' => ['zendesk', 'zopim'],
                'phrases' => ['static.zdassets.com', 'v2.zopim.com'],
                'linked_service_key' => null,
            ],
            'sb-calendly' => [
                'name' => 'Calendly',
                'type' => 'script_blocker',
                'provider' => 'Calendly LLC',
                'key' => 'sb-calendly',
                'purpose' => 'Blocks Calendly scheduling widget scripts.',
                'color' => 'indigo',
                'icon' => 'heroicon-o-calendar',
                'version' => '1.0.0',
                'handles' => ['calendly'],
                'phrases' => ['assets.calendly.com'],
                'linked_service_key' => null,
            ],
        ];
    }

    public static function getContentBlockerTemplates(): array
    {
        return [
            'cb-youtube' => [
                'name' => 'YouTube',
                'type' => 'content_blocker',
                'provider' => 'Google Ireland Limited',
                'key' => 'cb-youtube',
                'provider_key' => 'youtube',
                'purpose' => 'Blocks YouTube embedded videos until consent is given.',
                'color' => 'danger',
                'icon' => 'heroicon-o-video-camera',
                'version' => '1.0.0',
                'hosts' => ['youtube.com', 'youtu.be', 'youtube-nocookie.com', 'www.youtube.com'],
                'linked_service_key' => 'youtube',
                'placeholder' => [
                    'title' => 'YouTube Video',
                    'body' => 'Click to load the video. Your data will be sent to YouTube.',
                ],
            ],
            'cb-vimeo' => [
                'name' => 'Vimeo',
                'type' => 'content_blocker',
                'provider' => 'Vimeo.com, Inc.',
                'key' => 'cb-vimeo',
                'provider_key' => 'vimeo',
                'purpose' => 'Blocks Vimeo embedded videos until consent is given.',
                'color' => 'info',
                'icon' => 'heroicon-o-play',
                'version' => '1.0.0',
                'hosts' => ['vimeo.com', 'player.vimeo.com'],
                'linked_service_key' => 'vimeo',
                'placeholder' => [
                    'title' => 'Vimeo Video',
                    'body' => 'Click to load the video. Your data will be sent to Vimeo.',
                ],
            ],
            'cb-google-maps' => [
                'name' => 'Google Maps',
                'type' => 'content_blocker',
                'provider' => 'Google Ireland Limited',
                'key' => 'cb-google-maps',
                'provider_key' => 'google-maps',
                'purpose' => 'Blocks Google Maps embeds until consent is given.',
                'color' => 'success',
                'icon' => 'heroicon-o-map',
                'version' => '1.0.0',
                'hosts' => ['maps.google.com', 'www.google.com/maps', 'maps.googleapis.com'],
                'linked_service_key' => 'google-maps',
                'placeholder' => [
                    'title' => 'Google Maps',
                    'body' => 'Click to load the map. Your data will be sent to Google.',
                ],
            ],
            'cb-instagram' => [
                'name' => 'Instagram',
                'type' => 'content_blocker',
                'provider' => 'Meta Platforms Ireland Ltd.',
                'key' => 'cb-instagram',
                'provider_key' => 'instagram',
                'purpose' => 'Blocks Instagram embedded posts until consent is given.',
                'color' => 'rose',
                'icon' => 'heroicon-o-photo',
                'version' => '1.0.0',
                'hosts' => ['instagram.com', 'www.instagram.com', 'instagr.am'],
                'linked_service_key' => 'instagram',
                'placeholder' => [
                    'title' => 'Instagram Post',
                    'body' => 'Click to load the post. Your data will be sent to Instagram.',
                ],
            ],
            'cb-twitter' => [
                'name' => 'Twitter / X',
                'type' => 'content_blocker',
                'provider' => 'Twitter International Unlimited Company',
                'key' => 'cb-twitter',
                'provider_key' => 'x',
                'purpose' => 'Blocks Twitter/X embedded tweets until consent is given.',
                'color' => 'gray',
                'icon' => 'heroicon-o-chat-bubble-left',
                'version' => '1.0.0',
                'hosts' => ['twitter.com', 'x.com', 'platform.twitter.com'],
                'linked_service_key' => 'twitter',
                'placeholder' => [
                    'title' => 'Twitter / X Post',
                    'body' => 'Click to load the tweet. Your data will be sent to X.',
                ],
            ],
            'cb-soundcloud' => [
                'name' => 'SoundCloud',
                'type' => 'content_blocker',
                'provider' => 'SoundCloud Global Limited & Co. KG',
                'key' => 'cb-soundcloud',
                'provider_key' => 'soundcloud',
                'purpose' => 'Blocks SoundCloud embedded audio players until consent.',
                'color' => 'orange',
                'icon' => 'heroicon-o-musical-note',
                'version' => '1.0.0',
                'hosts' => ['soundcloud.com', 'w.soundcloud.com', 'api.soundcloud.com'],
                'linked_service_key' => null,
                'placeholder' => [
                    'title' => 'SoundCloud Audio',
                    'body' => 'Click to load the audio player. Your data will be sent to SoundCloud.',
                ],
            ],
            'cb-spotify' => [
                'name' => 'Spotify',
                'type' => 'content_blocker',
                'provider' => 'Spotify AB',
                'key' => 'cb-spotify',
                'provider_key' => 'spotify',
                'purpose' => 'Blocks Spotify embedded players until consent is given.',
                'color' => 'success',
                'icon' => 'heroicon-o-musical-note',
                'version' => '1.0.0',
                'hosts' => ['open.spotify.com', 'embed.spotify.com'],
                'linked_service_key' => null,
                'placeholder' => [
                    'title' => 'Spotify Player',
                    'body' => 'Click to load Spotify. Your data will be sent to Spotify.',
                ],
            ],
            'cb-openstreetmap' => [
                'name' => 'OpenStreetMap',
                'type' => 'content_blocker',
                'provider' => 'OpenStreetMap Foundation',
                'key' => 'cb-openstreetmap',
                'provider_key' => 'openstreetmap',
                'purpose' => 'Blocks OpenStreetMap embeds until consent is given.',
                'color' => 'emerald',
                'icon' => 'heroicon-o-map-pin',
                'version' => '1.0.0',
                'hosts' => ['openstreetmap.org', 'www.openstreetmap.org'],
                'linked_service_key' => null,
                'placeholder' => [
                    'title' => 'OpenStreetMap',
                    'body' => 'Click to load the map. Your data will be sent to OpenStreetMap.',
                ],
            ],

            // ── Additional Embed Providers ──────────────────────────────────

            'cb-tiktok' => [
                'name' => 'TikTok',
                'type' => 'content_blocker',
                'provider' => 'TikTok Technology Limited',
                'key' => 'cb-tiktok',
                'provider_key' => 'tiktok',
                'purpose' => 'Blocks TikTok embedded videos until consent is given.',
                'color' => 'fuchsia',
                'icon' => 'heroicon-o-play',
                'version' => '1.0.0',
                'hosts' => ['tiktok.com', 'www.tiktok.com'],
                'linked_service_key' => 'tiktok-pixel',
                'placeholder' => [
                    'title' => 'TikTok Video',
                    'body' => 'Click to load the video. Your data will be sent to TikTok.',
                ],
            ],
            'cb-facebook-video' => [
                'name' => 'Facebook Video',
                'type' => 'content_blocker',
                'provider' => 'Meta Platforms Ireland Ltd.',
                'key' => 'cb-facebook-video',
                'provider_key' => 'facebook',
                'purpose' => 'Blocks Facebook embedded videos and posts until consent.',
                'color' => 'info',
                'icon' => 'heroicon-o-video-camera',
                'version' => '1.0.0',
                'hosts' => ['facebook.com', 'www.facebook.com', 'web.facebook.com', 'fb.watch'],
                'linked_service_key' => 'facebook-pixel',
                'placeholder' => [
                    'title' => 'Facebook Content',
                    'body' => 'Click to load the content. Your data will be sent to Facebook.',
                ],
            ],
            'cb-reddit' => [
                'name' => 'Reddit',
                'type' => 'content_blocker',
                'provider' => 'Reddit, Inc.',
                'key' => 'cb-reddit',
                'provider_key' => 'reddit',
                'purpose' => 'Blocks Reddit embedded posts until consent is given.',
                'color' => 'orange',
                'icon' => 'heroicon-o-chat-bubble-left-right',
                'version' => '1.0.0',
                'hosts' => ['reddit.com', 'www.reddit.com', 'embed.reddit.com', 'www.redditmedia.com'],
                'linked_service_key' => null,
                'placeholder' => [
                    'title' => 'Reddit Post',
                    'body' => 'Click to load the post. Your data will be sent to Reddit.',
                ],
            ],
            'cb-dailymotion' => [
                'name' => 'Dailymotion',
                'type' => 'content_blocker',
                'provider' => 'Dailymotion SA',
                'key' => 'cb-dailymotion',
                'provider_key' => 'dailymotion',
                'purpose' => 'Blocks Dailymotion embedded videos until consent.',
                'color' => 'sky',
                'icon' => 'heroicon-o-play-circle',
                'version' => '1.0.0',
                'hosts' => ['dailymotion.com', 'www.dailymotion.com', 'geo.dailymotion.com'],
                'linked_service_key' => null,
                'placeholder' => [
                    'title' => 'Dailymotion Video',
                    'body' => 'Click to load the video. Your data will be sent to Dailymotion.',
                ],
            ],
            'cb-pinterest' => [
                'name' => 'Pinterest',
                'type' => 'content_blocker',
                'provider' => 'Pinterest, Inc.',
                'key' => 'cb-pinterest',
                'provider_key' => 'pinterest',
                'purpose' => 'Blocks Pinterest embedded pins and boards until consent.',
                'color' => 'danger',
                'icon' => 'heroicon-o-photo',
                'version' => '1.0.0',
                'hosts' => ['pinterest.com', 'www.pinterest.com', 'assets.pinterest.com', 'widgets.pinterest.com'],
                'linked_service_key' => 'pinterest-tag',
                'placeholder' => [
                    'title' => 'Pinterest Pin',
                    'body' => 'Click to load the pin. Your data will be sent to Pinterest.',
                ],
            ],
            'cb-linkedin' => [
                'name' => 'LinkedIn',
                'type' => 'content_blocker',
                'provider' => 'LinkedIn Ireland Unlimited Company',
                'key' => 'cb-linkedin',
                'provider_key' => 'linkedin',
                'purpose' => 'Blocks LinkedIn embedded posts and profiles until consent.',
                'color' => 'info',
                'icon' => 'heroicon-o-briefcase',
                'version' => '1.0.0',
                'hosts' => ['linkedin.com', 'www.linkedin.com'],
                'linked_service_key' => 'linkedin-insight',
                'placeholder' => [
                    'title' => 'LinkedIn Content',
                    'body' => 'Click to load the content. Your data will be sent to LinkedIn.',
                ],
            ],
            'cb-google-recaptcha' => [
                'name' => 'Google reCAPTCHA',
                'type' => 'content_blocker',
                'provider' => 'Google Ireland Limited',
                'key' => 'cb-google-recaptcha',
                'provider_key' => 'google',
                'purpose' => 'Blocks Google reCAPTCHA iframes until consent.',
                'color' => 'info',
                'icon' => 'heroicon-o-shield-check',
                'version' => '1.0.0',
                'hosts' => ['google.com/recaptcha', 'recaptcha.net'],
                'linked_service_key' => null,
                'placeholder' => [
                    'title' => 'Google reCAPTCHA',
                    'body' => 'Click to load reCAPTCHA. Your data will be sent to Google.',
                ],
            ],
            'cb-typeform' => [
                'name' => 'Typeform',
                'type' => 'content_blocker',
                'provider' => 'TYPEFORM SL',
                'key' => 'cb-typeform',
                'provider_key' => 'typeform',
                'purpose' => 'Blocks Typeform embedded forms until consent.',
                'color' => 'violet',
                'icon' => 'heroicon-o-clipboard-document-list',
                'version' => '1.0.0',
                'hosts' => ['typeform.com', 'form.typeform.com'],
                'linked_service_key' => null,
                'placeholder' => [
                    'title' => 'Typeform',
                    'body' => 'Click to load the form. Your data will be sent to Typeform.',
                ],
            ],
            'cb-calendly' => [
                'name' => 'Calendly',
                'type' => 'content_blocker',
                'provider' => 'Calendly LLC',
                'key' => 'cb-calendly',
                'provider_key' => 'calendly',
                'purpose' => 'Blocks Calendly embedded scheduling widgets until consent.',
                'color' => 'indigo',
                'icon' => 'heroicon-o-calendar',
                'version' => '1.0.0',
                'hosts' => ['calendly.com'],
                'linked_service_key' => null,
                'placeholder' => [
                    'title' => 'Calendly',
                    'body' => 'Click to load the scheduler. Your data will be sent to Calendly.',
                ],
            ],

            // ── Floating Widget Blockers (Live Chat etc.) ──────────────────

            'cb-tidio' => [
                'name' => 'Tidio Live Chat',
                'type' => 'content_blocker',
                'provider' => 'Tidio Ltd.',
                'key' => 'cb-tidio',
                'provider_key' => 'tidio',
                'purpose' => 'Blocks Tidio live chat widget until consent is given.',
                'color' => 'info',
                'icon' => 'heroicon-o-chat-bubble-bottom-center-text',
                'version' => '1.0.0',
                'hosts' => ['tidio.co', 'code.tidio.co', 'widget-v4.tidiochat.com'],
                'linked_service_key' => null,
                'display_mode' => 'floating',
                'floating_position' => 'bottom-right',
                'placeholder' => [
                    'title' => 'Tidio Live Chat',
                    'body' => 'Allow Tidio to enable the live chat widget.',
                ],
            ],
            'cb-intercom' => [
                'name' => 'Intercom Messenger',
                'type' => 'content_blocker',
                'provider' => 'Intercom, Inc.',
                'key' => 'cb-intercom',
                'provider_key' => 'intercom',
                'purpose' => 'Blocks Intercom messenger widget until consent is given.',
                'color' => 'info',
                'icon' => 'heroicon-o-chat-bubble-bottom-center-text',
                'version' => '1.0.0',
                'hosts' => ['intercom.io', 'widget.intercom.io', 'js.intercomcdn.com'],
                'linked_service_key' => null,
                'display_mode' => 'floating',
                'floating_position' => 'bottom-right',
                'placeholder' => [
                    'title' => 'Intercom Messenger',
                    'body' => 'Allow Intercom to enable the messenger widget.',
                ],
            ],
            'cb-crisp' => [
                'name' => 'Crisp Chat',
                'type' => 'content_blocker',
                'provider' => 'Crisp IM SAS',
                'key' => 'cb-crisp',
                'provider_key' => 'crisp',
                'purpose' => 'Blocks Crisp live chat widget until consent is given.',
                'color' => 'violet',
                'icon' => 'heroicon-o-chat-bubble-bottom-center-text',
                'version' => '1.0.0',
                'hosts' => ['crisp.chat', 'client.crisp.chat'],
                'linked_service_key' => null,
                'display_mode' => 'floating',
                'floating_position' => 'bottom-right',
                'placeholder' => [
                    'title' => 'Crisp Chat',
                    'body' => 'Allow Crisp to enable the live chat widget.',
                ],
            ],
            'cb-zendesk-chat' => [
                'name' => 'Zendesk Chat',
                'type' => 'content_blocker',
                'provider' => 'Zendesk, Inc.',
                'key' => 'cb-zendesk-chat',
                'provider_key' => 'zendesk',
                'purpose' => 'Blocks Zendesk chat widget until consent is given.',
                'color' => 'success',
                'icon' => 'heroicon-o-chat-bubble-bottom-center-text',
                'version' => '1.0.0',
                'hosts' => ['zopim.com', 'static.zdassets.com', 'ekr.zdassets.com'],
                'linked_service_key' => null,
                'display_mode' => 'floating',
                'floating_position' => 'bottom-right',
                'placeholder' => [
                    'title' => 'Zendesk Chat',
                    'body' => 'Allow Zendesk to enable the chat widget.',
                ],
            ],
            'cb-hubspot-chat' => [
                'name' => 'HubSpot Chat',
                'type' => 'content_blocker',
                'provider' => 'HubSpot, Inc.',
                'key' => 'cb-hubspot-chat',
                'provider_key' => 'hubspot-chat',
                'purpose' => 'Blocks HubSpot live chat widget until consent is given.',
                'color' => 'orange',
                'icon' => 'heroicon-o-chat-bubble-bottom-center-text',
                'version' => '1.0.0',
                'hosts' => ['js.usemessages.com', 'js.hubspot.com', 'app.hubspot.com'],
                'linked_service_key' => null,
                'display_mode' => 'floating',
                'floating_position' => 'bottom-right',
                'placeholder' => [
                    'title' => 'HubSpot Chat',
                    'body' => 'Allow HubSpot to enable the live chat widget.',
                ],
            ],
        ];
    }

    public static function getStyleBlockerTemplates(): array
    {
        return [
            'stb-google-fonts' => [
                'name' => 'Google Fonts',
                'type' => 'style_blocker',
                'provider' => 'Google Ireland Limited',
                'key' => 'stb-google-fonts',
                'purpose' => 'Blocks Google Fonts loading from external CDN until consent is given.',
                'color' => 'info',
                'icon' => 'heroicon-o-language',
                'version' => '1.0.0',
                'handles' => ['google-fonts'],
                'phrases' => ['fonts.googleapis.com', 'fonts.gstatic.com'],
                'linked_service_key' => null,
            ],
            'stb-adobe-fonts' => [
                'name' => 'Adobe Fonts (Typekit)',
                'type' => 'style_blocker',
                'provider' => 'Adobe Inc.',
                'key' => 'stb-adobe-fonts',
                'purpose' => 'Blocks Adobe Fonts / Typekit loading until consent is given.',
                'color' => 'danger',
                'icon' => 'heroicon-o-language',
                'version' => '1.0.0',
                'handles' => ['adobe-fonts', 'typekit'],
                'phrases' => ['use.typekit.net', 'p.typekit.net'],
                'linked_service_key' => null,
            ],
            'stb-fontawesome-cdn' => [
                'name' => 'Font Awesome CDN',
                'type' => 'style_blocker',
                'provider' => 'Fonticons, Inc.',
                'key' => 'stb-fontawesome-cdn',
                'purpose' => 'Blocks Font Awesome CDN stylesheet loading until consent is given.',
                'color' => 'sky',
                'icon' => 'heroicon-o-paint-brush',
                'version' => '1.0.0',
                'handles' => ['font-awesome'],
                'phrases' => ['cdnjs.cloudflare.com/ajax/libs/font-awesome', 'use.fontawesome.com', 'kit.fontawesome.com'],
                'linked_service_key' => null,
            ],
        ];
    }
}
